# Built-in
output_dir:      "output"
index_filenames: [ 'index.html', 'index.php' ]
data_sources:
  - type: filesystem_compact
    items_root: '/'
    layouts_root: '/'

# Custom
assets_base_url:  'http://static.mystonline.com'
base_url:         'http://mystonline.com'
